services:
  - type: web
    name: cybernaut-edutech
    env: python
    buildCommand: "pip install -r requirements.txt && python seed_data.py"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.18
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: 0 