services:
  - type: web
    name: soundhar-edutech
    env: python
    buildCommand: "pip install -r requirements.txt && python seed_data.py"
    startCommand: "gunicorn app:app"
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: 0 