"""Initial migration with all models.

Revision ID: 8e0a393bbdd8
Revises: 
Create Date: 2025-06-21 19:14:48.457589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0a393bbdd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_lectures', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('instructor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instructor_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instructor_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('what_youll_learn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('course_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))

    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('feedback',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('feedback',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('course_id')
        batch_op.drop_column('company')
        batch_op.drop_column('position')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('requirements')
        batch_op.drop_column('course_content')
        batch_op.drop_column('what_youll_learn')
        batch_op.drop_column('instructor_bio')
        batch_op.drop_column('instructor_title')
        batch_op.drop_column('instructor_name')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('total_reviews')
        batch_op.drop_column('rating')
        batch_op.drop_column('total_lectures')
        batch_op.drop_column('level')
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
